//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:2.0.50727.5420
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JsonTools.Properties {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強型別資源類別
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JsonTools.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強型別資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap _03146_intothelight_1920x1080 {
            get {
                object obj = ResourceManager.GetObject("03146_intothelight_1920x1080", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1195445190322000997molumen_red_round_error_warning_icon_svg_med {
            get {
                object obj = ResourceManager.GetObject("1195445190322000997molumen_red_round_error_warning_icon.svg.med", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Deleket_Soft_Scraps_Button_Refresh {
            get {
                object obj = ResourceManager.GetObject("Deleket-Soft-Scraps-Button-Refresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 ##1.0.0.0
        ///**2013/04/10
        ///1. 新版本發布，有任何問題或要加功能可以MAIL到erric@digiwin.biz
        ///
        ///##1.0.0.1
        ///**2013/04/10
        ///1. 修正載入兩次以上的TXT時，節點沒有清除的錯誤
        ///
        ///##1.0.0.2
        ///**2013/04/10
        ///1. 增加進階查詢功能，可以自訂複合查詢NAME，VALUE，PATH
        ///
        ///##1.0.0.3
        ///**2013/04/11
        ///1. 修正點擊查詢後的GRID資料所顯示的PATH缺少一層的錯誤
        ///
        ///##1.0.0.4
        ///**2013/04/11
        ///1. 增加搜尋空字串時的提示
        ///
        ///##1.0.0.5
        ///**2013/04/11
        ///1. 增加載入的TXT FILE判斷
        ///
        ///##1.0.0.6
        ///**2013/04/16
        ///1. 增加即時查功能，可以自訂即時查條件
        ///
        ///##1.0.0.7
        ///**2013/04/17
        ///1. 增加變數監看功能
        ///
        ///##1.0.0.8
        ///**2013/04/30
        ///1. 增加開發用頁籤，內藏懶人用轉換字串
        ///
        ///##1.0.0.9
        ///**2013/04/30
        ///1. 增加Se [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string JSonInfo {
            get {
                return ResourceManager.GetString("JSonInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 [34]
        ///單店庫存查詢=DSCPOSQ01
        ///跨店庫存查詢=DSCPOSQ02
        ///轉撥單查詢=DSCPOSQ04
        ///公告查詢=DSCPOSQ05
        ///會員查詢=DSCPOSQ06
        ///當日查詢/當班查詢=DSCPOSQ07
        ///交易查詢=DSCPOSQ08
        ///選擇品號=DSCPOSQ09
        ///商品顏色尺寸選擇=DSCPOSQ10
        ///門市銷售日統計查詢=DSCPOSQ13
        ///付款方式統計查詢=DSCPOSQ13
        ///交易類別統計查詢=DSCPOSQ13
        ///品號銷售日統計查詢=DSCPOSQ13
        ///類別銷售日統計查詢=DSCPOSQ13
        ///時段統計查詢=DSCPOSQ13
        ///品號時段統計查詢=DSCPOSQ13
        ///類別時段統計查詢=DSCPOSQ13
        ///業務員業績查詢=DSCPOSQ13
        ///沖銷應收=DSCPOSQ14
        ///關單=DSCPOSQ15
        ///圖片查詢=DSCPOSQ18
        ///發票跳號查詢=DSCPOSQ19
        ///團務查詢=DSCPOSQ20
        ///預購查詢(新版)=DSCPOSQ21
        ///變更歷程查詢=DSCPOSQ22
        ///電子計算機發票=DSCPOSV01
        ///銷貨退回單=DSCPOSV02
        ///銷貨單=DSCPOSV03        /// [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string PGName {
            get {
                return ResourceManager.GetString("PGName", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Untitled___1 {
            get {
                object obj = ResourceManager.GetObject("Untitled - 1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
